{"name": "LOGIN", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Must provide a selector when finding elements\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Must provide a selector when finding elements\n    at getResponseForW3CError (e:\\Users\\85810\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (e:\\Users\\85810\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"E:\\Users\\85810\\PycharmProjects\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"E:\\Users\\85810\\PycharmProjects\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\log_in_steps.py\", line 32, in step_impl\n    login_in_screen.get_text_of_element()\n  File \"e:\\Users\\85810\\PycharmProjects\\baz_behave\\baz_behave\\Behave\\utils\\common_actions.py\", line 25, in get_text_of_element\n    return self.driver.find_element(*locator).text\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\Users\\85810\\PycharmProjects\\venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 409, in find_element\n    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\Users\\85810\\PycharmProjects\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\Users\\85810\\PycharmProjects\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 122, in check_response\n    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\n"}, "steps": [{"name": "Given estamos en la pantalla de inicio", "status": "passed", "start": 1687902978443, "stop": 1687902978444}, {"name": "When ingresa usuario", "status": "passed", "start": 1687902978444, "stop": 1687902980285}, {"name": "When ingresa contraseña", "status": "passed", "start": 1687902980285, "stop": 1687902981398}, {"name": "When damos clic al botón", "status": "passed", "start": 1687902981398, "stop": 1687902982071}, {"name": "Then entramos a la app \"SWAGLABS\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Must provide a selector when finding elements\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Must provide a selector when finding elements\n    at getResponseForW3CError (e:\\Users\\85810\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (e:\\Users\\85810\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"E:\\Users\\85810\\PycharmProjects\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"E:\\Users\\85810\\PycharmProjects\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\log_in_steps.py\", line 32, in step_impl\n    login_in_screen.get_text_of_element()\n  File \"e:\\Users\\85810\\PycharmProjects\\baz_behave\\baz_behave\\Behave\\utils\\common_actions.py\", line 25, in get_text_of_element\n    return self.driver.find_element(*locator).text\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\Users\\85810\\PycharmProjects\\venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 409, in find_element\n    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\Users\\85810\\PycharmProjects\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\Users\\85810\\PycharmProjects\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 122, in check_response\n    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\n"}, "start": 1687902982072, "stop": 1687902982101}], "start": 1687902970003, "stop": 1687902982575, "uuid": "36bf6c5f-806b-4e33-8fb1-392a0916fa82", "historyId": "ab5f10435539244f688df0a801a2061f", "fullName": "Log In: LOGIN", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "smoke"}, {"name": "feature", "value": "Log In"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}